"""add source and gmail_thread_id to applications

Revision ID: 07253e632dc6
Revises: aae38b16342b
Create Date: 2026-06-30 12:49:22.358664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07253e632dc6'
down_revision: Union[str, None] = 'aae38b16342b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=20), nullable=False, server_default='manual'))
        batch_op.add_column(sa.Column('gmail_thread_id', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_applications_gmail_thread_id'), ['gmail_thread_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_gmail_thread_id'))
        batch_op.drop_column('gmail_thread_id')
        batch_op.drop_column('source')

    # ### end Alembic commands ###
